version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5600:5600"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

